# Generated by Django 4.2.19 on 2025-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(help_text='Укажите номер стола для заказа', verbose_name='Номер стола')),
                ('items', models.JSONField(help_text='Список блюд с ценами в формате JSON', verbose_name='Список блюд')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Автоматически рассчитанная стоимость заказа', max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='waiting', help_text='Текущий статус заказа', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
