# Generated by Django 4.2.19 on 2025-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название блюда (например, "Кофе", "Бургер")', max_length=100, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену блюда (в валюте)', max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, help_text='Необязательное описание блюда (например, ингредиенты)', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Автоматически рассчитанная стоимость заказа', max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(help_text='Выберите блюда, включенные в заказ', to='orders.dish', verbose_name='Блюда'),
        ),
    ]
