# Generated by Django 4.2.19 on 2025-02-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_dishes_delete_dish_order_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время, когда заказ был оплачен', null=True, verbose_name='Дата оплаты'),
        ),
    ]
