# Generated by Django 4.2.19 on 2025-02-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.JSONField(default=list, verbose_name='Блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
